language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"

sudo: false

env:
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=master

matrix:
    fast_finish: true
    exclude:
      - python: "2.7"
        env: DJANGO=master
      - python: "2.7"
        env: DJANGO=2.0
      - python: "3.4"
        env: DJANGO=master
      - python: "3.4"
        env: DJANGO=2.0

    allow_failures:
      - env: DJANGO=master
      - python: "pypy"
      - python: "pypy3"

install:
    - pip install tox tox-travis

script:
    - tox

notifications:
    email: false
