language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"

sudo: false

env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=master

matrix:
    fast_finish: true
    include:
      - python: "3.7"
        env: DJANGO=2.0
        sudo: required
        dist: xenial
      - python: "3.7"
        env: DJANGO=2.1
        sudo: required
        dist: xenial
      - python: "3.7"
        env: DJANGO=master
        sudo: required
        dist: xenial
    exclude:
      - python: "2.7"
        env: DJANGO=master
      - python: "2.7"
        env: DJANGO=2.0
      - python: "2.7"
        env: DJANGO=2.1
      - python: "3.4"
        env: DJANGO=master
      - python: "3.4"
        env: DJANGO=2.0
      - python: "3.4"
        env: DJANGO=2.1
      - python: "3.6"
        env: DJANGO=1.8
      - python: "3.6"
        env: DJANGO=1.9
      - python: "3.6"
        env: DJANGO=1.10

    allow_failures:
      - env: DJANGO=master
      - python: "pypy"
      - python: "pypy3"

install:
    - pip install tox tox-travis

script:
    - tox

notifications:
    email: false
